/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-01 09:34:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.makepage_002dhsw;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Properties;

public final class findPassword_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/templates/makepage-hsw/../mainpageSeo/header.jsp", Long.valueOf(1682842268627L));
    _jspx_dependants.put("/templates/makepage-hsw/../mainpageSeo/footer.jsp", Long.valueOf(1682068001331L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Properties");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- findPassword.user -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>비밀번호 찾기</title>\r\n");
      out.write("</head>\r\n");
      out.write("<link href=\"../../static/image/logo/logo.png\" rel=\"shortcut icon\" type=\"image/x-icon\">\r\n");
      out.write("\r\n");
      out.write("<!-- 개인 css -->\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/singupcss-hsw/basic.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/singupcss-hsw/term.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/singupcss-hsw/info.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/static/css/singupcss-hsw/modal.css\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<!-- 폰트 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- 로고 -->\r\n");
      out.write("<link href=\"../../static/image/logo/logo.png\" rel=\"shortcut icon\" type=\"image/x-icon\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../../static/css/mainpageSeo/hf.css\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"home\">\r\n");
      out.write("<div class=\"h__cov-progress\" style=\"background-color: rgb(0, 199, 174); opacity: 0; position: fixed; top: 0px; left: 0px; width: 0%; height: 2px; transition: opacity 0.6s ease 0s;\"></div>\r\n");
      out.write("		<header id=\"app-header\" class=\"h_global-header\" data-v-50506024=\"\">\r\n");
      out.write("			<div data-v-5f10666f=\"\" data-v-50506024=\"\"\r\n");
      out.write("				class=\"h-global-navigation-bar\">\r\n");
      out.write("				<!-- 섹션태그때문에 이미지가 나오지 않아서 없애버렸어요 -->\r\n");
      out.write("				<div data-v-5f10666f=\"\" class=\"h-desktop-header\">\r\n");
      out.write("					<div data-v-5f10666f=\"\" class=\"left-section\" style=\"margin-right: 250px\">\r\n");
      out.write("						<div data-v-5f10666f=\"\" class=\"logo\">\r\n");
      out.write("							<a data-v-5f10666f=\"\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/listOk.board\" class=\"\"> <img\r\n");
      out.write("								data-v-5f10666f=\"\"\r\n");
      out.write("								src=\"../../static/image/logo/JOONGSHIN.svg\"\r\n");
      out.write("								alt=\"숨고, 숨은고수\">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<nav data-v-5f10666f=\"\">\r\n");
      out.write("							<ul data-v-5f10666f=\"\" class=\"nav-list\">\r\n");
      out.write("								<li data-v-5f10666f=\"\" class=\"nav-item left-section-item\"><a\r\n");
      out.write("									data-v-5f10666f=\"\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/comulistOk.board\">\r\n");
      out.write("									<span data-v-5f10666f=\"\">커뮤니티</span></a></li>\r\n");
      out.write("								<li data-v-5f10666f=\"\" class=\"nav-item left-section-item\"><a\r\n");
      out.write("									data-v-5f10666f=\"\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("									<span data-v-5f10666f=\"\">문의 게시판</span></a></li>\r\n");
      out.write("						\r\n");
      out.write("							</ul>\r\n");
      out.write("						</nav>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!--  					 로고,문자열 네개까지 ↑ -->\r\n");
      out.write("					");
      out.write("\r\n");
      out.write("					<!-- 로그인 회원가입 고수가입 전↑ -->\r\n");
      out.write("					<div data-v-5f10666f=\"\" class=\"right-section\">\r\n");
      out.write("						<nav data-v-5f10666f=\"\">\r\n");
      out.write("							<ul data-v-5f10666f=\"\" class=\"nav-list\">\r\n");
      out.write("								<li data-v-5f10666f=\"\" class=\"nav-item right-section-item\" style=\"margin-right: 40px;\"><a\r\n");
      out.write("									data-v-5f10666f=\"\" href=\"/login.user\" class=\"gnb-link\"><span\r\n");
      out.write("										data-v-5f10666f=\"\">로그인</span></a> <!----></li>\r\n");
      out.write("								<li data-v-5f10666f=\"\" class=\"nav-item right-section-item\" style=\"margin-right: 40px;\"><a\r\n");
      out.write("									href=\"/join.user\"\r\n");
      out.write("									class=\"gnb-link\"><span data-v-5f10666f=\"\">회원가입</span></a> <!----></li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</nav>\r\n");
      out.write("						<button data-v-5f10666f=\"\" type=\"button\"\r\n");
      out.write("							class=\"h-btn pro-signup-h-btn right-section-item h-btn-primary h-btn-primary2\">\r\n");
      out.write("							<a data-v-5f10666f=\"\" href=\"/gosuLogin.juniorUser\" class=\"\">주니어 가입</a>\r\n");
      out.write("						</button>\r\n");
      out.write("						<!---->\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- 헤더 전체 div 닫는부분 -->\r\n");
      out.write("				<!-- 없애버린 세션 태그 닫는자리 -->\r\n");
      out.write("			</div>\r\n");
      out.write("		</header>\r\n");
      out.write("		<!-- 헤더 끝 -->\r\n");
      out.write("		</div>\r\n");
      out.write("		</body>\r\n");
      out.write("</html>\r\n");
      out.write("		\r\n");
      out.write("		");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<main id=\"join\">\r\n");
      out.write("        <div class=\"modal\">\r\n");
      out.write("            <div class=\"warn-modal\">\r\n");
      out.write("                <div id=\"content-wrap\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <section id=\"join-container\">\r\n");
      out.write("                <h2 id=\"title\">\r\n");
      out.write("                    아이디 재설정\r\n");
      out.write("                </h2>\r\n");
      out.write("            \r\n");
      out.write("	<h1>비밀번호 찾기</h1>\r\n");
      out.write("	<form action=\"/FindPassword.board\" method=\"post\">	\r\n");
      out.write("		<div class=\"info\">\r\n");
      out.write("			<div class=\"info-container\">\r\n");
      out.write("				<span style=\"margin-bottom: 5%;\">\r\n");
      out.write("					<input maxlength=\"30\" id=\"email\" name=\"userEmail\" type=\"email\" autocomplete=\"off\" placeholder=\"example@joongsin.com\">\r\n");
      out.write("				</span>\r\n");
      out.write("				<small class=\"notice\">가입하신 이메일 주소를 입력해주시면 새로운 비밀번호를 설정 가능한 링크를 보내드립니다.</small>\r\n");
      out.write("				<p class=\"help\"></p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"join\">\r\n");
      out.write("			<button type=\"submit\" class=\"next1\">이메일 전송하기</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	</section>\r\n");
      out.write("	</main>\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("<script>let contextPath = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../../static/css/mainpageSeo/hf.css\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<footer>\r\n");
      out.write("			<nav id=\"app-footer\" class=\"footer-container\" data-v-4e4965bd=\"\">\r\n");
      out.write("				<div class=\"footer-container-row container\" data-v-4e4965bd=\"\">\r\n");
      out.write("					<div class=\"col-content margin-bottom\" data-v-4e4965bd=\"\">\r\n");
      out.write("						<p class=\"text contact\" data-v-4e4965bd=\"\">1599-5319</p>\r\n");
      out.write("						<p class=\"text-middle\" data-v-4e4965bd=\"\">\r\n");
      out.write("							평일 10:00 - 18:00<br data-v-4e4965bd=\"\">(점심시간 13:00 - 14:00\r\n");
      out.write("							제외 · 주말/공휴일 제외)\r\n");
      out.write("						</p>\r\n");
      out.write("						<a class=\"download\" data-v-4e4965bd=\"\"\r\n");
      out.write("							href=\"https://soomgoapp.onelink.me/6cqv?af_channel=cpc&amp;af_dp=smgo%3A%2F%2Fhome%2F&amp;af_keywords=%EC%88%A8%EA%B3%A0&amp;af_sub2=%EB%A9%94%EC%9D%B8&amp;af_sub4=footer&amp;af_web_dp=https%3A%2F%2Fsoomgo.com%2Fapp-download%2Fsender&amp;c=%EB%A9%94%EC%9D%B8&amp;pid=google\"><img\r\n");
      out.write("							src=\"https://assets.cdn.soomgo.com/icons/icon-download-appstore.svg\"\r\n");
      out.write("							alt=\"앱스토어\" data-v-4e4965bd=\"\">APP STORE </a><a class=\"download\"\r\n");
      out.write("							data-v-4e4965bd=\"\"\r\n");
      out.write("							href=\"https://soomgoapp.onelink.me/6cqv?af_channel=cpc&amp;af_dp=smgo%3A%2F%2Fhome%2F&amp;af_keywords=%EC%88%A8%EA%B3%A0&amp;af_sub2=%EB%A9%94%EC%9D%B8&amp;af_sub4=footer&amp;af_web_dp=https%3A%2F%2Fsoomgo.com%2Fapp-download%2Fsender&amp;c=%EB%A9%94%EC%9D%B8&amp;pid=google\"><img\r\n");
      out.write("							src=\"https://assets.cdn.soomgo.com/icons/icon-download-palystore.svg\"\r\n");
      out.write("							alt=\"구글플레이\" data-v-4e4965bd=\"\">PLAY STORE </a>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"col-content right\" data-v-4e4965bd=\"\">\r\n");
      out.write("						<ul class=\"content-list\" data-v-4e4965bd=\"\">\r\n");
      out.write("							<li data-v-4e4965bd=\"\" class=\"open-padding\"><span\r\n");
      out.write("								class=\"text-middle title category\" data-v-4e4965bd=\"\">\r\n");
      out.write("									중신소개 <span class=\"new-badge\" style=\"display: none;\"\r\n");
      out.write("									data-v-4e4965bd=\"\">N</span>\r\n");
      out.write("								<!---->\r\n");
      out.write("							</span>\r\n");
      out.write("							<div style=\"\" data-v-4e4965bd=\"\">\r\n");
      out.write("									<a href=\"/about\" class=\"text-middle category\"\r\n");
      out.write("										data-v-4e4965bd=\"\"> 회사소개 <span class=\"new-badge\"\r\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\r\n");
      out.write("										href=\"https://soomgo.career.greetinghr.com/\"\r\n");
      out.write("										class=\"text-middle category\" data-v-4e4965bd=\"\"> 채용안내 <span\r\n");
      out.write("										class=\"new-badge\" style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\r\n");
      out.write("										href=\"https://blog.soomgo.com\" class=\"text-middle category\"\r\n");
      out.write("										data-v-4e4965bd=\"\"> 팀블로그 <span class=\"new-badge\"\r\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a>\r\n");
      out.write("								</div></li>\r\n");
      out.write("							<li data-v-4e4965bd=\"\" class=\"open-padding\"><span\r\n");
      out.write("								class=\"text-middle title category\" data-v-4e4965bd=\"\">\r\n");
      out.write("									고객안내 <span class=\"new-badge\" style=\"display: none;\"\r\n");
      out.write("									data-v-4e4965bd=\"\">N</span>\r\n");
      out.write("								<!---->\r\n");
      out.write("							</span>\r\n");
      out.write("							<div style=\"\" data-v-4e4965bd=\"\">\r\n");
      out.write("									<a href=\"/how-it-works\" class=\"text-middle category\"\r\n");
      out.write("										data-v-4e4965bd=\"\"> 이용안내 <span class=\"new-badge\"\r\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\r\n");
      out.write("										href=\"/safety\" class=\"text-middle category\" data-v-4e4965bd=\"\">\r\n");
      out.write("										안전정책 <span class=\"new-badge\" style=\"display: none;\"\r\n");
      out.write("										data-v-4e4965bd=\"\">N</span>\r\n");
      out.write("									</a><a href=\"/prices\" class=\"text-middle category\"\r\n");
      out.write("										data-v-4e4965bd=\"\"> 예상금액 <span class=\"new-badge\"\r\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\r\n");
      out.write("										href=\"/search/pro?from=footer\" class=\"text-middle category\"\r\n");
      out.write("										data-v-4e4965bd=\"\"> 주니어찾기 <span class=\"new-badge\"\r\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\r\n");
      out.write("										href=\"https://help.soomgo.com/hc/ko/articles/360056329911\"\r\n");
      out.write("										class=\"text-middle category\" data-v-4e4965bd=\"\"> 주니어보증 <span\r\n");
      out.write("										class=\"new-badge\" style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\r\n");
      out.write("										href=\"/questions/\" class=\"text-middle category\"\r\n");
      out.write("										data-v-4e4965bd=\"\"> 주니어에게묻다 <span class=\"new-badge\"\r\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\r\n");
      out.write("										href=\"/community/soomgo-life/all\"\r\n");
      out.write("										class=\"text-middle category sr-only\" data-v-4e4965bd=\"\">\r\n");
      out.write("										커뮤니티 <span class=\"new-badge\" style=\"display: none;\"\r\n");
      out.write("										data-v-4e4965bd=\"\">N</span>\r\n");
      out.write("									</a>\r\n");
      out.write("								</div></li>\r\n");
      out.write("							<li data-v-4e4965bd=\"\" class=\"open-padding\"><span\r\n");
      out.write("								class=\"text-middle title category\" data-v-4e4965bd=\"\">\r\n");
      out.write("									주니어안내 <span class=\"new-badge\" style=\"display: none;\"\r\n");
      out.write("									data-v-4e4965bd=\"\">N</span>\r\n");
      out.write("								<!---->\r\n");
      out.write("							</span>\r\n");
      out.write("							<div style=\"\" data-v-4e4965bd=\"\">\r\n");
      out.write("									<a href=\"/how-soomgo-works\" class=\"text-middle category\"\r\n");
      out.write("										data-v-4e4965bd=\"\"> 이용안내 <span class=\"new-badge\"\r\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\r\n");
      out.write("										href=\"https://help.soomgo.com/hc/ko/categories/115001218027\"\r\n");
      out.write("										class=\"text-middle category\" data-v-4e4965bd=\"\"> 주니어가이드 <span\r\n");
      out.write("										class=\"new-badge\" style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\r\n");
      out.write("										href=\"/pro\" class=\"text-middle category\" data-v-4e4965bd=\"\">\r\n");
      out.write("										주니어가입 <span class=\"new-badge\" style=\"display: none;\"\r\n");
      out.write("										data-v-4e4965bd=\"\">N</span>\r\n");
      out.write("									</a><a href=\"/pro-center\" class=\"text-middle category\"\r\n");
      out.write("										data-v-4e4965bd=\"\"> 주니어센터 <span class=\"new-badge\"\r\n");
      out.write("										style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a>\r\n");
      out.write("								</div></li>\r\n");
      out.write("							<li data-v-4e4965bd=\"\" class=\"open-padding\"><span\r\n");
      out.write("								class=\"text-middle title category\" data-v-4e4965bd=\"\">\r\n");
      out.write("									고객센터 <span class=\"new-badge\" style=\"display: none;\"\r\n");
      out.write("									data-v-4e4965bd=\"\">N</span>\r\n");
      out.write("								<!---->\r\n");
      out.write("							</span>\r\n");
      out.write("							<div style=\"\" data-v-4e4965bd=\"\">\r\n");
      out.write("									<a\r\n");
      out.write("										href=\"https://help.soomgo.com/hc/ko/categories/360002081551-%EA%B3%B5%EC%A7%80%EC%82%AC%ED%95%AD\"\r\n");
      out.write("										class=\"text-middle category\" data-v-4e4965bd=\"\"> 공지사항 <span\r\n");
      out.write("										class=\"new-badge\" style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a><a\r\n");
      out.write("										href=\"https://help.soomgo.com/hc/ko\"\r\n");
      out.write("										class=\"text-middle category\" data-v-4e4965bd=\"\"> 자주묻는질문 <span\r\n");
      out.write("										class=\"new-badge\" style=\"display: none;\" data-v-4e4965bd=\"\">N</span></a>\r\n");
      out.write("								</div></li>\r\n");
      out.write("						</ul>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"footer-container-row container terms\" data-v-4e4965bd=\"\">\r\n");
      out.write("					<div class=\"term-container\" data-v-4e4965bd=\"\">\r\n");
      out.write("						<div class=\"col-content term-content\" data-v-4e4965bd=\"\">\r\n");
      out.write("							<div class=\"col-content-list-term\" data-v-4e4965bd=\"\">\r\n");
      out.write("								<div class=\"terms-group\" data-v-4e4965bd=\"\">\r\n");
      out.write("									<a href=\"/terms/usage\" class=\"text term\" data-v-4e4965bd=\"\">이용약관</a><a\r\n");
      out.write("										href=\"/terms/privacy\" class=\"text term\" data-v-4e4965bd=\"\">개인정보처리방침</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"terms-group\" data-v-4e4965bd=\"\">\r\n");
      out.write("									<a href=\"/terms/location\" class=\"text term\" data-v-4e4965bd=\"\">위치기반\r\n");
      out.write("										서비스 이용약관</a><a target=\"_blank\" rel=\"nofollow\"\r\n");
      out.write("										href=\"https://www.ftc.go.kr/bizCommPop.do?wrkr_no=1208822325\"\r\n");
      out.write("										class=\"text term\" data-v-4e4965bd=\"\"> 사업자 정보확인 </a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"col-content-list-term\" data-v-4e4965bd=\"\">\r\n");
      out.write("								<span class=\"text term-text\" data-v-4e4965bd=\"\">\r\n");
      out.write("									(주)브레이브모바일은 통신판매중개자로서 통신판매의 당사자가 아니며 개별 판매자가 제공하는 서비스에 대한 이행,\r\n");
      out.write("									계약사항 등과 관련한 의무와 책임은 거래당사자에게 있습니다. </span>\r\n");
      out.write("							</div>\r\n");
      out.write("							<ul class=\"col-content-guide\" data-v-4e4965bd=\"\">\r\n");
      out.write("								<li class=\"text\" data-v-4e4965bd=\"\">상호명:(주)브레이브모바일 ·\r\n");
      out.write("									대표이사:KIM ROBIN H · 개인정보책임관리자:김태우 · 주소:서울특별시 강남구 테헤란로 415, L7\r\n");
      out.write("									강남타워 5층</li>\r\n");
      out.write("								<li class=\"text\" data-v-4e4965bd=\"\">사업자등록번호:120-88-22325 ·\r\n");
      out.write("									통신판매업신고증:제 2021-서울강남-00551 호 · 직업정보제공사업 신고번호:서울청 제 2019-21호</li>\r\n");
      out.write("								<li class=\"text\" data-v-4e4965bd=\"\">고객센터:1599-5319 ·\r\n");
      out.write("									이메일:support@soomgo.com</li>\r\n");
      out.write("								<li class=\"text\" data-v-4e4965bd=\"\">Copyright ©Brave Mobile\r\n");
      out.write("									Inc. All Rights Reserved.</li>\r\n");
      out.write("							</ul>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"col-content badge-list right\" data-v-4e4965bd=\"\">\r\n");
      out.write("							<a href=\"https://www.facebook.com/SoomgoKorea/\" target=\"_blank\"\r\n");
      out.write("								class=\"footer-badge\" data-v-4e4965bd=\"\"><img\r\n");
      out.write("								src=\"https://assets.cdn.soomgo.com/icons/icon-footer-sns-facebook.svg\"\r\n");
      out.write("								alt=\"주니어 페이스북 계정\" data-v-4e4965bd=\"\"></a><a\r\n");
      out.write("								href=\"https://www.instagram.com/soomgo_official/\"\r\n");
      out.write("								target=\"_blank\" class=\"footer-badge\" data-v-4e4965bd=\"\"><img\r\n");
      out.write("								src=\"https://assets.cdn.soomgo.com/icons/icon-footer-sns-instagram.svg\"\r\n");
      out.write("								alt=\"주니어 인스타그램\" data-v-4e4965bd=\"\"></a><a\r\n");
      out.write("								href=\"https://blog.naver.com/brave_mobile_mkt/\" target=\"_blank\"\r\n");
      out.write("								class=\"footer-badge\" data-v-4e4965bd=\"\"><img\r\n");
      out.write("								src=\"https://assets.cdn.soomgo.com/icons/icon-footer-sns-naverblog.svg\"\r\n");
      out.write("								alt=\"주니어 블로그\" data-v-4e4965bd=\"\"></a><a\r\n");
      out.write("								href=\"https://post.naver.com/brave_mobile_mkt?isHome=1\"\r\n");
      out.write("								target=\"_blank\" class=\"footer-badge\" data-v-4e4965bd=\"\"><img\r\n");
      out.write("								src=\"https://assets.cdn.soomgo.com/icons/icon-footer-sns-naverpost.svg\"\r\n");
      out.write("								alt=\"주니어 포스트\" data-v-4e4965bd=\"\"></a><a\r\n");
      out.write("								href=\"https://news.soomgo.com\" target=\"_blank\"\r\n");
      out.write("								class=\"footer-badge\" data-v-4e4965bd=\"\"><img\r\n");
      out.write("								src=\"https://assets.cdn.soomgo.com/icons/icon-footer-sns-tistory.svg\"\r\n");
      out.write("								alt=\"주니어 스토리\" data-v-4e4965bd=\"\"></a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</nav>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 전체 div -->\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
