/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-01 08:49:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.templates.mypage_002djin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class password_002dchange_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/study/web_1900_shs/joongshin/workspace/joongshin/WebContent/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1682054622792L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link href=\"../../static/image/logo/logo.png\" rel=\"shortcut icon\" type=\"image/x-icon\">\r\n");
      out.write("<title>중고신입 비밀번호 변경</title>\r\n");
      out.write("<!--폰트 -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"../../static/css/mypage-css-jin/password-change.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* 잘못된 값 입력시 배경 빨강으로 만들어줌 */\r\n");
      out.write("    .is-invalid {\r\n");
      out.write("        border-color: red;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div id=\"app-body\">\r\n");
      out.write("		<div class=\"container container-md\">\r\n");
      out.write("		<form  action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/myPwChangeOk.mypage\" name=\"updatePw\" method=\"post\">\r\n");
      out.write("			<main class=\"account-info-container\">\r\n");
      out.write("				<h1>비밀번호 변경</h1>\r\n");
      out.write("				<div  \r\n");
      out.write("					class=\"sign-container secondary lg\" style=\"display: none;\">\r\n");
      out.write("					<div  class=\"header\">\r\n");
      out.write("						<div  class=\"title\">\r\n");
      out.write("							<img src=\"data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMCIgaGVpZ2h0PSIyMCIgdmlld0JveD0iMCAwIDIwIDIwIj4KICAgIDxnIGZpbGw9Im5vbmUiIGZpbGwtcnVsZT0iZXZlbm9kZCI+CiAgICAgICAgPGc+CiAgICAgICAgICAgIDxnPgogICAgICAgICAgICAgICAgPGc+CiAgICAgICAgICAgICAgICAgICAgPHBhdGggZD0iTTAgMEwyMCAwIDIwIDIwIDAgMjB6IiB0cmFuc2Zvcm09InRyYW5zbGF0ZSgtMzIgLTMwMSkgdHJhbnNsYXRlKDE2IDI4MSkgdHJhbnNsYXRlKDE2IDIwKSIvPgogICAgICAgICAgICAgICAgICAgIDxwYXRoIGZpbGw9IiMzMjMyMzIiIGZpbGwtcnVsZT0ibm9uemVybyIgZD0iTTEwIDJjLTQuNDE2IDAtOCAzLjU4NC04IDhzMy41ODQgOCA4IDggOC0zLjU4NCA4LTgtMy41ODQtOC04LTh6bS44IDEySDkuMlY5LjJoMS42VjE0em0wLTYuNEg5LjJWNmgxLjZ2MS42eiIgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTMyIC0zMDEpIHRyYW5zbGF0ZSgxNiAyODEpIHRyYW5zbGF0ZSgxNiAyMCkiLz4KICAgICAgICAgICAgICAgIDwvZz4KICAgICAgICAgICAgPC9nPgogICAgICAgIDwvZz4KICAgIDwvZz4KPC9zdmc+Cg==\"\r\n");
      out.write("								alt=\"secondary\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-row\">\r\n");
      out.write("					<div  class=\"margin-bottom-24 col-12\">\r\n");
      out.write("						<fieldset class=\"form-group current-password\" id=\"__BVID__422\">\r\n");
      out.write("						  <legend tabindex=\"-1\" class=\"bv-no-focus-ring col-form-label pt-0\" id=\"__BVID__422__BV_label_\">기존 비밀번호</legend>\r\n");
      out.write("						  <div>\r\n");
      out.write("						    <div role=\"group\" class=\"input-group1 current-password\">\r\n");
      out.write("						      <input name=\"currentPassword\" type=\"password\" placeholder=\"현재 비밀번호를 입력해주세요\" autocomplete=\"off\" class=\"form-control1\" autocapitalize=\"off\" spellcheck=\"false\" data-vv-validate-on=\"blur\" aria-invalid=\"true\" id=\"currentPassword\" >\r\n");
      out.write("						      <button type=\"button\" class=\"btn btn-secondary\">표시</button>\r\n");
      out.write("						    </div>\r\n");
      out.write("						    <div id=\"message\"></div>\r\n");
      out.write("						  </div>\r\n");
      out.write("						</fieldset>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"margin-bottm-8 col-12\">\r\n");
      out.write("					  <fieldset class=\"form-group\" id=\"__BVID__424\">\r\n");
      out.write("					    <legend tabindex=\"-1\" class=\"bv-no-focus-ring col-form-label pt-0\" id=\"__BVID__424__BV_label_\">새로운 비밀번호</legend>\r\n");
      out.write("					    <div>\r\n");
      out.write("					      <input name=\"newPassword\" id=\"newPassword\" type=\"password\" placeholder=\"영문+숫자 조합 8자리 이상 입력해주세요\" autocomplete=\"off\" class=\"form-control1\" autocapitalize=\"off\" spellcheck=\"false\" data-vv-validate-on=\"blur\" aria-invalid=\"true\" id=\"__BVID__425\" aria-required=\"true\">\r\n");
      out.write("					      <div id=\"passwordMessage\"></div>\r\n");
      out.write("					    </div>\r\n");
      out.write("					  </fieldset>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"margin-bottm-8 col-12\">\r\n");
      out.write("					  <fieldset class=\"form-group\" id=\"__BVID__426\">\r\n");
      out.write("					    <legend tabindex=\"-1\" class=\"bv-no-focus-ring col-form-label pt-0\" id=\"__BVID__426__BV_label_\">새로운 비밀번호 확인</legend>\r\n");
      out.write("					    <div>\r\n");
      out.write("					      <input name=\"confirmPassword\" id=\"confirmPassword\" type=\"password\" placeholder=\"비밀번호를 한번 더 입력해주세요\" autocomplete=\"off\" class=\"form-control1\" autocapitalize=\"off\" spellcheck=\"false\" aria-invalid=\"true\" aria-required=\"true\">\r\n");
      out.write("					      <div id=\"confirmPasswordMessage\"></div>\r\n");
      out.write("					    </div>\r\n");
      out.write("					  </fieldset>\r\n");
      out.write("					</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<footer class=\"button-group\">\r\n");
      out.write("						<a href=\"javascript:history.go(-1)\"\r\n");
      out.write("							class=\"btn btn-cancel btn-active btn-outline-secondary\"\r\n");
      out.write("							target=\"_self\" style=\"color: #6FB6C0;\">취소</a>\r\n");
      out.write("						<button type=\"button\" class=\"btn btn-primary\" onclick=\"submit()\">변경 완료</button>\r\n");
      out.write("					</footer>	\r\n");
      out.write("				</main>\r\n");
      out.write("			</form>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../mainpageSeo/footer.jsp", out, false);
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.4.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("/*비밀번호 유효성 검사*/\r\n");
      out.write("const currentPasswordInput = document.querySelector('input[name=\"currentPassword\"]');\r\n");
      out.write("const message = document.querySelector('#message');\r\n");
      out.write("const newPasswordInput = document.querySelector('input[name=\"password\"]');\r\n");
      out.write("const confirmPasswordInput = document.querySelector('input[name=\"confirmPassword\"]');\r\n");
      out.write("const newPasswordMessage = document.querySelector('#passwordMessage');\r\n");
      out.write("const confirmPasswordMessage = document.querySelector('#confirmPasswordMessage');\r\n");
      out.write("const showPasswordButton = document.querySelector('.current-password button');\r\n");
      out.write("\r\n");
      out.write("let checkPw = false;\r\n");
      out.write("\r\n");
      out.write("/*기존 비밀번호 입력 */\r\n");
      out.write("function validatePassword() {\r\n");
      out.write("  	if (currentPasswordInput.value.trim() === '') {\r\n");
      out.write("	    message.innerText = '비밀번호를 입력해주세요.';\r\n");
      out.write("	    message.style.color = 'red';\r\n");
      out.write("	    currentPasswordInput.classList.add(\"is-invalid\");\r\n");
      out.write("	    return true;\r\n");
      out.write("  	} else {\r\n");
      out.write("		checkPw = false;\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url: \"checkPwOk.mypage\",\r\n");
      out.write("			data: {inputUserPassword: currentPasswordInput.value},\r\n");
      out.write("			async: false,\r\n");
      out.write("			success: function(result) {\r\n");
      out.write("				result = JSON.parse(result);\r\n");
      out.write("				if(result.check) {\r\n");
      out.write("					// 일치하다\r\n");
      out.write("					message.innerHTML = \"\";\r\n");
      out.write("	  				currentPasswordInput.classList.remove(\"is-invalid\");\r\n");
      out.write("					checkPw = true;\r\n");
      out.write("				} else {\r\n");
      out.write("					message.innerText = '기존 비밀번호와 다릅니다';\r\n");
      out.write("				    message.style.color = 'red';\r\n");
      out.write("				    currentPasswordInput.classList.add(\"is-invalid\");\r\n");
      out.write("					checkPw = false;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function submit() {\r\n");
      out.write("	if (validatePassword() && validatePasswordInputs()) {\r\n");
      out.write("    	document.updatePw.submit();\r\n");
      out.write("  	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 새로운 비밀번호 입력 */\r\n");
      out.write("\r\n");
      out.write("function validateNewPassword() {\r\n");
      out.write("  const newPasswordValue = newPasswordInput.value;\r\n");
      out.write("  if (!newPasswordValue) {\r\n");
      out.write("    newPasswordMessage.innerText = '비밀번호를 입력해주세요.';\r\n");
      out.write("    newPasswordMessage.style.color = 'red';\r\n");
      out.write("    newPasswordInput.classList.add(\"is-invalid\");\r\n");
      out.write("    \r\n");
      out.write("    return false;\r\n");
      out.write("  }\r\n");
      out.write("  if (!/^(?=.*[a-zA-Z])(?=.*[0-9]).{8,}$/.test(newPasswordValue)) {\r\n");
      out.write("    newPasswordMessage.innerText = '영문+숫자 조합 8자리 이상 입력해주세요.';\r\n");
      out.write("    newPasswordMessage.style.color = 'red';\r\n");
      out.write("    newPasswordInput.classList.add(\"is-invalid\");\r\n");
      out.write("    return false;\r\n");
      out.write("  }else{\r\n");
      out.write("	  newPasswordMessage.innerHTML = \"\";\r\n");
      out.write("	newPasswordInput.classList.remove('is-invalid');\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* 새로운 비밀번호 확인 */\r\n");
      out.write("\r\n");
      out.write("function validateConfirmPassword() {\r\n");
      out.write("  const newPasswordValue = newPasswordInput.value;\r\n");
      out.write("  const confirmPasswordValue = confirmPasswordInput.value;\r\n");
      out.write("  if (newPasswordValue !== confirmPasswordValue) {\r\n");
      out.write("    confirmPasswordMessage.innerText = '비밀번호가 일치하지 않습니다.';\r\n");
      out.write("    confirmPasswordMessage.style.color = 'red';\r\n");
      out.write("    confirmPasswordInput.classList.add(\"is-invalid\");\r\n");
      out.write("    return false;\r\n");
      out.write("  }else{\r\n");
      out.write("	  confirmPasswordMessage.innerText = \"\";\r\n");
      out.write("	  confirmPasswordInput.classList.remove(\"is-invalid\");\r\n");
      out.write("	  \r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validatePasswordInputs() {\r\n");
      out.write("  return validateNewPassword() && validateConfirmPassword();\r\n");
      out.write("}\r\n");
      out.write("/* 입력화면에서 벗어나면 즉시 값반영해서 맞는지 아닌지 판별 */\r\n");
      out.write("currentPasswordInput.addEventListener('blur', validatePassword);\r\n");
      out.write("newPasswordInput.addEventListener('blur', validateNewPassword);\r\n");
      out.write("confirmPasswordInput.addEventListener('blur', validateConfirmPassword);\r\n");
      out.write("\r\n");
      out.write("/* 비밀번호 표시 */\r\n");
      out.write("showPasswordButton.addEventListener('click', () => {\r\n");
      out.write("  const type = currentPasswordInput.type === 'password' ? 'text' : 'password';\r\n");
      out.write("  currentPasswordInput.type = type;\r\n");
      out.write("  showPasswordButton.classList.toggle('show');\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /templates/mypage-jin/password-change.jsp(27,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("userId");
      // /templates/mypage-jin/password-change.jsp(27,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userId}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("  ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("  ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /templates/mypage-jin/password-change.jsp(30,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty userId}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    ");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../mainpageSeo/loginHeader.jsp", out, false);
          out.write("\r\n");
          out.write("  ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest)_jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse)_jspx_page_context.getResponse();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("    ");
          org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../mainpageSeo/header.jsp", out, false);
          out.write("\r\n");
          out.write("  ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
